databases:
  - name: budgetapp
    databaseName: budgetapp_rx0n
    user: budgetapp_rx0n_user

services:
  - type: web
    name: kcbudgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp_rx0n
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false